-- =============================================================
-- GENESIS — Supabase Database Schema
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor)
-- =============================================================

-- 1. Analysis Jobs
CREATE TABLE IF NOT EXISTS analysis_jobs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename      TEXT NOT NULL DEFAULT 'unknown.vcf',
  genome_build  TEXT NOT NULL DEFAULT 'GRCh38',
  status        TEXT NOT NULL DEFAULT 'pending',
  is_demo       BOOLEAN NOT NULL DEFAULT FALSE,
  total_variants INTEGER DEFAULT 0,
  total_claims   INTEGER DEFAULT 0,
  supported_claims INTEGER DEFAULT 0,
  unsupported_claims INTEGER DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at  TIMESTAMPTZ
);

-- 2. Variants (one per variant per job)
CREATE TABLE IF NOT EXISTS variants (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id        UUID NOT NULL REFERENCES analysis_jobs(id) ON DELETE CASCADE,
  chrom         TEXT NOT NULL,
  pos           BIGINT NOT NULL,
  ref_allele    TEXT NOT NULL,
  alt_allele    TEXT NOT NULL,
  rsid          TEXT,
  gene          TEXT,
  variant_key   TEXT NOT NULL,
  clinvar_sig   TEXT,
  gnomad_af     DOUBLE PRECISION,
  consequence   TEXT,
  genome_build  TEXT NOT NULL DEFAULT 'GRCh38',
  info          JSONB DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Evidence Items (per variant, per source)
CREATE TABLE IF NOT EXISTS evidence_items (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  variant_id    UUID NOT NULL REFERENCES variants(id) ON DELETE CASCADE,
  source        TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  url           TEXT,
  data          JSONB DEFAULT '{}',
  retrieved_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_demo_data  BOOLEAN NOT NULL DEFAULT FALSE,
  error_message TEXT
);

-- 4. Claims (generated by Research Agent)
CREATE TABLE IF NOT EXISTS claims (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  variant_id            UUID NOT NULL REFERENCES variants(id) ON DELETE CASCADE,
  claim_text            TEXT NOT NULL,
  source                TEXT NOT NULL,
  source_url            TEXT,
  confidence            DOUBLE PRECISION DEFAULT 0.0,
  verification_verdict  TEXT,
  verification_reasoning TEXT,
  verification_confidence DOUBLE PRECISION,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Reports (one per job, generated by Report Agent)
CREATE TABLE IF NOT EXISTS reports (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id             UUID NOT NULL REFERENCES analysis_jobs(id) ON DELETE CASCADE,
  summary            TEXT NOT NULL DEFAULT '',
  disclaimer         TEXT NOT NULL DEFAULT '',
  total_variants     INTEGER DEFAULT 0,
  total_claims       INTEGER DEFAULT 0,
  supported_claims   INTEGER DEFAULT 0,
  unsupported_claims INTEGER DEFAULT 0,
  conflicts          JSONB DEFAULT '[]',
  sources_used       TEXT[] DEFAULT '{}',
  limitations        TEXT[] DEFAULT '{}',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. Variant Summaries (per-variant summary from Report Agent)
CREATE TABLE IF NOT EXISTS variant_summaries (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id     UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  variant_id    UUID NOT NULL REFERENCES variants(id) ON DELETE CASCADE,
  summary       TEXT NOT NULL DEFAULT '',
  conflicts     JSONB DEFAULT '[]',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_variants_job_id ON variants(job_id);
CREATE INDEX IF NOT EXISTS idx_evidence_variant_id ON evidence_items(variant_id);
CREATE INDEX IF NOT EXISTS idx_claims_variant_id ON claims(variant_id);
CREATE INDEX IF NOT EXISTS idx_reports_job_id ON reports(job_id);
CREATE INDEX IF NOT EXISTS idx_variant_summaries_report_id ON variant_summaries(report_id);
CREATE INDEX IF NOT EXISTS idx_analysis_jobs_created_at ON analysis_jobs(created_at DESC);

-- Enable Row Level Security (public read for demo)
ALTER TABLE analysis_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE variant_summaries ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (backend uses service key)
CREATE POLICY "Service role full access" ON analysis_jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON variants FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON evidence_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON claims FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON variant_summaries FOR ALL USING (true) WITH CHECK (true);
