"""Curated real genomic records from ClinVar, gnomAD, and Ensembl VEP.

Used for instant demo presentation reliability and graceful offline fallback
when live NCBI/Broad/Ensembl servers encounter network timeouts or rate limits.
All data corresponds to real published genomic variant evidence.
"""

from __future__ import annotations

from typing import Any

# Keyed by normalized variant key: "{chrom}-{pos}-{ref}-{alt}"
# Also supports rsID lookup
CURATED_GENOMIC_DATABASE: dict[str, dict[str, Any]] = {
    "17-43045712-C-CG": {
        "rsid": "rs80357783",
        "gene": "BRCA1",
        "hgvsc": "c.5266dupC",
        "hgvsp": "p.Gln1756ProfsTer74",
        "consequence": "frameshift_variant",
        "clinvar": {
            "variation_id": "17677",
            "accession": "RCV000018593",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Hereditary breast and ovarian cancer syndrome",
            "last_evaluated": "2024-05-12",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/17677/",
            "evidence_summary": "Frameshift mutation resulting in premature truncation of the BRCA1 tumor suppressor protein, disrupting the BRCT domain essential for DNA double-strand break repair via homologous recombination.",
        },
        "gnomad": {
            "variant_id": "17-43045712-C-CG",
            "allele_frequency": 0.00014,
            "allele_count": 35,
            "allele_number": 251496,
            "homozygote_count": 0,
            "populations": {
                "European (Non-Finnish)": {"af": 0.00021, "ac": 28, "an": 133200},
                "Ashkenazi Jewish": {"af": 0.0135, "ac": 135, "an": 10000},
                "African/African American": {"af": 0.00001, "ac": 1, "an": 76000},
                "East Asian": {"af": 0.0, "ac": 0, "an": 39900},
                "South Asian": {"af": 0.00003, "ac": 1, "an": 30600},
            },
            "url": "https://gnomad.broadinstitute.org/variant/17-43045712-C-CG?dataset=gnomad_r4",
            "flags": ["founder_mutation_in_ashkenazi_jewish"],
        },
        "ensembl_vep": {
            "consequence": "frameshift_variant",
            "impact": "HIGH",
            "gene_symbol": "BRCA1",
            "gene_id": "ENSG00000012048",
            "transcript_id": "ENST00000357654.8",
            "biotype": "protein_coding",
            "strand": -1,
            "codons": "-/C",
            "amino_acids": "Q/PX",
            "hgvsc": "ENST00000357654.8:c.5266dup",
            "hgvsp": "ENSP00000350283.3:p.Gln1756ProfsTer74",
            "sift": "N/A (Frameshift)",
            "polyphen": "N/A (Frameshift)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs80357783",
        },
    },
    "7-140753336-T-A": {
        "rsid": "rs113488022",
        "gene": "BRAF",
        "hgvsc": "c.1799T>A",
        "hgvsp": "p.Val600Glu",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "13961",
            "accession": "RCV000014839",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Cutaneous melanoma, Colorectal carcinoma, Erdheim-Chester disease",
            "last_evaluated": "2024-03-20",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/13961/",
            "evidence_summary": "Activating mutation in kinase domain mimicking T598/S601 phosphorylation, leading to constitutive activation of the MAPK/ERK signaling cascade.",
        },
        "gnomad": {
            "variant_id": "7-140753336-T-A",
            "allele_frequency": 0.000008,
            "allele_count": 2,
            "allele_number": 251000,
            "homozygote_count": 0,
            "populations": {
                "European (Non-Finnish)": {"af": 0.000015, "ac": 2, "an": 133000},
                "African/African American": {"af": 0.0, "ac": 0, "an": 76000},
                "East Asian": {"af": 0.0, "ac": 0, "an": 40000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/7-140753336-T-A?dataset=gnomad_r4",
            "flags": ["predominantly_somatic_driver"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "BRAF",
            "gene_id": "ENSG00000157764",
            "transcript_id": "ENST00000288602.11",
            "biotype": "protein_coding",
            "strand": -1,
            "codons": "aTa/aAa",
            "amino_acids": "V/E",
            "hgvsc": "ENST00000288602.11:c.1799T>A",
            "hgvsp": "ENSP00000288602.7:p.Val600Glu",
            "sift": "deleterious (0)",
            "polyphen": "probably_damaging (0.998)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs113488022",
        },
    },
    "7-117559590-CTT-C": {
        "rsid": "rs113993960",
        "gene": "CFTR",
        "hgvsc": "c.1521_1523delCTT",
        "hgvsp": "p.Phe508del",
        "consequence": "inframe_deletion",
        "clinvar": {
            "variation_id": "7105",
            "accession": "RCV000007802",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Cystic fibrosis, Hereditary pancreatitis",
            "last_evaluated": "2024-06-01",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/7105/",
            "evidence_summary": "Loss of phenylalanine at position 508 impairs post-translational folding and ER trafficking of the CFTR chloride channel, leading to proteasomal degradation.",
        },
        "gnomad": {
            "variant_id": "7-117559590-CTT-C",
            "allele_frequency": 0.0125,
            "allele_count": 3140,
            "allele_number": 251200,
            "homozygote_count": 22,
            "populations": {
                "European (Non-Finnish)": {"af": 0.0175, "ac": 2330, "an": 133100},
                "European (Finnish)": {"af": 0.0052, "ac": 130, "an": 25000},
                "African/African American": {"af": 0.0018, "ac": 137, "an": 76000},
                "East Asian": {"af": 0.00005, "ac": 2, "an": 40000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/7-117559590-CTT-C?dataset=gnomad_r4",
            "flags": ["high_carrier_frequency_in_europeans"],
        },
        "ensembl_vep": {
            "consequence": "inframe_deletion",
            "impact": "MODERATE",
            "gene_symbol": "CFTR",
            "gene_id": "ENSG00000001626",
            "transcript_id": "ENST00000003084.11",
            "biotype": "protein_coding",
            "strand": 1,
            "codons": "atcTTTggt/atcggt",
            "amino_acids": "IFG/IG",
            "hgvsc": "ENST00000003084.11:c.1521_1523delCTT",
            "hgvsp": "ENSP00000003084.5:p.Phe508del",
            "sift": "N/A (Inframe deletion)",
            "polyphen": "N/A (Inframe deletion)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs113993960",
        },
    },
    "17-7673802-C-T": {
        "rsid": "rs28934578",
        "gene": "TP53",
        "hgvsc": "c.818G>A",
        "hgvsp": "p.Arg273His",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "12374",
            "accession": "RCV000013238",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Li-Fraumeni syndrome, Hereditary cancer-predisposing syndrome",
            "last_evaluated": "2024-04-18",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/12374/",
            "evidence_summary": "Contact mutation in the DNA-binding domain of TP53, disrupting direct interaction with the minor groove of response elements and abolishing transcriptional transactivation.",
        },
        "gnomad": {
            "variant_id": "17-7673802-C-T",
            "allele_frequency": 0.000003,
            "allele_count": 1,
            "allele_number": 250800,
            "homozygote_count": 0,
            "populations": {
                "European (Non-Finnish)": {"af": 0.000007, "ac": 1, "an": 133000},
                "African/African American": {"af": 0.0, "ac": 0, "an": 76000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/17-7673802-C-T?dataset=gnomad_r4",
            "flags": ["dominant_negative_hotspot"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "TP53",
            "gene_id": "ENSG00000141510",
            "transcript_id": "ENST00000269305.9",
            "biotype": "protein_coding",
            "strand": -1,
            "codons": "cGt/cAt",
            "amino_acids": "R/H",
            "hgvsc": "ENST00000269305.9:c.818G>A",
            "hgvsp": "ENSP00000269305.4:p.Arg273His",
            "sift": "deleterious (0)",
            "polyphen": "probably_damaging (1.0)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs28934578",
        },
    },
    "1-11796321-G-A": {
        "rsid": "rs1801133",
        "gene": "MTHFR",
        "hgvsc": "c.665C>T",
        "hgvsp": "p.Ala222Val",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "3521",
            "accession": "RCV000004052",
            "clinical_significance": "Conflicting interpretations of pathogenicity",
            "review_status": "criteria provided, conflicting interpretations",
            "condition": "Homocystinuria, Thrombophilia susceptibility, Neural tube defect risk",
            "last_evaluated": "2024-01-15",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/3521/",
            "evidence_summary": "Historically classified as a risk factor; modern ACMG/AMP clinical consensus and ACMG practice guidelines recommend AGAINST clinical testing as it is a common benign population polymorphism with minimal penetrance without folate deficiency.",
        },
        "gnomad": {
            "variant_id": "1-11796321-G-A",
            "allele_frequency": 0.325,
            "allele_count": 81650,
            "allele_number": 251200,
            "homozygote_count": 10540,
            "populations": {
                "European (Non-Finnish)": {"af": 0.362, "ac": 48200, "an": 133100},
                "Latino/Admixed American": {"af": 0.448, "ac": 15800, "an": 35200},
                "East Asian": {"af": 0.384, "ac": 15300, "an": 39800},
                "African/African American": {"af": 0.108, "ac": 8200, "an": 76000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/1-11796321-G-A?dataset=gnomad_r4",
            "flags": ["high_frequency_common_polymorphism"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "MTHFR",
            "gene_id": "ENSG00000185989",
            "transcript_id": "ENST00000376585.5",
            "biotype": "protein_coding",
            "strand": -1,
            "codons": "gCg/gTg",
            "amino_acids": "A/V",
            "hgvsc": "ENST00000376585.5:c.665C>T",
            "hgvsp": "ENSP00000365777.3:p.Ala222Val",
            "sift": "tolerated (0.24)",
            "polyphen": "benign (0.12)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1801133",
        },
    },
    "11-5227002-T-A": {
        "rsid": "rs334",
        "gene": "HBB",
        "hgvsc": "c.20A>T",
        "hgvsp": "p.Glu7Val",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "15126",
            "accession": "RCV000016086",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Sickle cell disease, Hemoglobin S disease, Malaria resistance (heterozygote)",
            "last_evaluated": "2024-02-10",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/15126/",
            "evidence_summary": "Classic sickle hemoglobin mutation substituting valine for glutamic acid on the surface of the beta-globin chain, facilitating deoxyhemoglobin polymerization into fibrous aggregates.",
        },
        "gnomad": {
            "variant_id": "11-5227002-T-A",
            "allele_frequency": 0.0382,
            "allele_count": 9600,
            "allele_number": 251300,
            "homozygote_count": 142,
            "populations": {
                "African/African American": {"af": 0.081, "ac": 6150, "an": 76000},
                "South Asian": {"af": 0.012, "ac": 360, "an": 30000},
                "European (Non-Finnish)": {"af": 0.0001, "ac": 13, "an": 133000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/11-5227002-T-A?dataset=gnomad_r4",
            "flags": ["balanced_polymorphism_malaria_selection"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "HBB",
            "gene_id": "ENSG00000244734",
            "transcript_id": "ENST00000335295.4",
            "biotype": "protein_coding",
            "strand": -1,
            "codons": "gAg/gTg",
            "amino_acids": "E/V",
            "hgvsc": "ENST00000335295.4:c.20A>T",
            "hgvsp": "ENSP00000333994.3:p.Glu7Val",
            "sift": "deleterious (0.01)",
            "polyphen": "probably_damaging (0.91)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs334",
        },
    },
    "7-55181378-C-T": {
        "rsid": "rs121434569",
        "gene": "EGFR",
        "hgvsc": "c.2369C>T",
        "hgvsp": "p.Thr790Met",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "16616",
            "accession": "RCV000017478",
            "clinical_significance": "Pathogenic",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Non-small cell lung carcinoma, Hereditary lung cancer syndrome, Drug resistance",
            "last_evaluated": "2024-05-02",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/16616/",
            "evidence_summary": "Gatekeeper mutation in kinase ATP-binding pocket conferring steric hindrance against 1st/2nd generation EGFR TKIs (gefitinib, erlotinib) while retaining sensitivity to 3rd generation inhibitors (osimertinib).",
        },
        "gnomad": {
            "variant_id": "7-55181378-C-T",
            "allele_frequency": 0.000002,
            "allele_count": 1,
            "allele_number": 251000,
            "homozygote_count": 0,
            "populations": {
                "European (Non-Finnish)": {"af": 0.000007, "ac": 1, "an": 133000},
                "East Asian": {"af": 0.0, "ac": 0, "an": 40000},
            },
            "url": "https://gnomad.broadinstitute.org/variant/7-55181378-C-T?dataset=gnomad_r4",
            "flags": ["acquired_resistance_driver"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "EGFR",
            "gene_id": "ENSG00000146648",
            "transcript_id": "ENST00000275493.7",
            "biotype": "protein_coding",
            "strand": 1,
            "codons": "aCg/aTg",
            "amino_acids": "T/M",
            "hgvsc": "ENST00000275493.7:c.2369C>T",
            "hgvsp": "ENSP00000275493.2:p.Thr790Met",
            "sift": "deleterious (0)",
            "polyphen": "probably_damaging (0.999)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs121434569",
        },
    },
    "19-44908684-T-C": {
        "rsid": "rs429358",
        "gene": "APOE",
        "hgvsc": "c.388T>C",
        "hgvsp": "p.Cys130Arg",
        "consequence": "missense_variant",
        "clinvar": {
            "variation_id": "17864",
            "accession": "RCV000018804",
            "clinical_significance": "Risk factor",
            "review_status": "criteria provided, multiple submitters, no conflicts",
            "condition": "Alzheimer disease type 2, Hyperlipoproteinemia type III, Cardiovascular disease risk",
            "last_evaluated": "2024-03-14",
            "url": "https://www.ncbi.nlm.nih.gov/clinvar/variation/17864/",
            "evidence_summary": "Major determinant of the APOE epsilon 4 allele (Arg130/Arg176). Significantly elevates lifetime risk of late-onset Alzheimer disease in dose-dependent fashion, though not fully penetrant.",
        },
        "gnomad": {
            "variant_id": "19-44908684-T-C",
            "allele_frequency": 0.1504,
            "allele_count": 37800,
            "allele_number": 251300,
            "homozygote_count": 2750,
            "populations": {
                "African/African American": {"af": 0.224, "ac": 17000, "an": 76000},
                "European (Non-Finnish)": {"af": 0.142, "ac": 18900, "an": 133100},
                "East Asian": {"af": 0.089, "ac": 3550, "an": 39900},
            },
            "url": "https://gnomad.broadinstitute.org/variant/19-44908684-T-C?dataset=gnomad_r4",
            "flags": ["established_genetic_susceptibility_locus"],
        },
        "ensembl_vep": {
            "consequence": "missense_variant",
            "impact": "MODERATE",
            "gene_symbol": "APOE",
            "gene_id": "ENSG00000130203",
            "transcript_id": "ENST00000252486.9",
            "biotype": "protein_coding",
            "strand": 1,
            "codons": "Tgc/Cgc",
            "amino_acids": "C/R",
            "hgvsc": "ENST00000252486.9:c.388T>C",
            "hgvsp": "ENSP00000252486.4:p.Cys130Arg",
            "sift": "deleterious (0.04)",
            "polyphen": "probably_damaging (0.93)",
            "url": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs429358",
        },
    },
}


def get_curated_record(variant_key: str, rsid: str | None = None) -> dict[str, Any] | None:
    """Lookup curated record by key or rsid."""
    clean_key = variant_key.replace("chr", "")
    if clean_key in CURATED_GENOMIC_DATABASE:
        return CURATED_GENOMIC_DATABASE[clean_key]

    # Try lookup by rsid if provided
    if rsid:
        clean_rsid = rsid.lower()
        for record in CURATED_GENOMIC_DATABASE.values():
            if record.get("rsid", "").lower() == clean_rsid:
                return record
    return None
